### PR TITLE
Enforcing `VERIFY_PEER` on the client

### LINKED ISSUE #4: ssl_certificate never used in Client
Prove me wrong, but I think the `ssl_certificate` is never used in client.

So the connection to a server doesn't get validated?

### PR DESCRIPTION
**Pull request by ph**
The ruby client did not enforce the validation of the certificate,
opening possible man in the middle attacks on the client. This PR make sure that
the `verify_mode` is set to `VERIFY_PEER` and add the certificate to the store
for this specific connection. An integration test was added to validate
this change.

This change makes the ruby client handling of connection closer to the
`logstash-forwarder` behavior, which does the verify peer per default.

Fixes #4

### CODE REVIEW

**Comment by ph** [comment]
Small cleanups in the dependencies and how we specify the files in the gemspec.

File: spec/integration_spec.rb [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+      server.run { |data| queue.push(data) }
+    end
+  end
+
+  it "should require a certificate" do
+    expect { 
+      client = Lumberjack::Client.new(:port => port, 
+                             :host => host,
+                             :addresses => host,
+                             :ssl_certificate => certificate_file_crt)
```
Comment (jsvd) [inline spec/integration_spec.rb]: no need for a ssl_key parameter on the client side?

Comment (ph) [inline spec/integration_spec.rb]: Well the client use the public key to encrypt which is available in the certificate and the server use the private key to decrypt it? The ssl_key was never a requirement in the `logstash-output-lumberjack`. But yes the LSF has an optional key option in the config, I'll check it more.

Comment (ph) [inline spec/integration_spec.rb]: https://github.com/elastic/logstash-forwarder/blob/master/publisher1.go#L137

I'll check on the ruby side, I am +1 on having the same behavior, I need to investigate what it's actually do.

Comment (ph) [inline spec/integration_spec.rb]: http://www.hydrogen18.com/blog/your-own-pki-tls-golang.html A lot of nice information ;)

**Comment by ph** [comment]
Thanks @jsvd for the comment, I'll do a bit more thinking.

File: spec/integration_spec.rb (hunk 1 above)
Comment (jordansissel) [inline spec/integration_spec.rb]: we don't currently require a client certificate, it's optional.

File: spec/integration_spec.rb [hunk 2]
```diff
@@ -0,0 +1,57 @@
+# encoding: utf-8
+require "lib/lumberjack/client"
```
Comment (jordansissel) [inline spec/integration_spec.rb]: remove the 'lib/' part here

File: spec/integration_spec.rb [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+require "lib/lumberjack/server"
```
Comment (jordansissel) [inline spec/integration_spec.rb]: Remove the 'lib/' part here

**Comment by jordansissel** [comment]
Added some inline comments. Tests pass (`bundle exec rspec`) once the `lib/` part is removed as I commented.

Let's get expected-rejection cases added also (client connects to a server that is not trusted, etc)

File: spec/integration_spec.rb (hunk 2 above)
Comment (ph) [inline spec/integration_spec.rb]: :disappointed: by myself on that

**Comment by ph** [comment]
@jordansissel I have added another test to cover a not trusted server.
This PR requires a new release of ruby-flores with https://github.com/jordansissel/ruby-flores/pull/3

**Comment by ph** [comment]
updated with @jordansissel comments.

**Comment by jordansissel** [comment]
Tests passing.
